fix
  CC      arch/powerpc/kernel/setup_64.o
../arch/powerpc/kernel/setup_64.c:266:13: error: no previous prototype
for 'record_spr_defaults' [-Werror=missing-prototypes]
 void __init record_spr_defaults(void)