Fix
../arch/powerpc/kernel/trace/ftrace.c:978:7: error: no previous
prototype for ‘arch_ftrace_match_adjust’ [-Werror=missing-prototypes]
 char *arch_ftrace_match_adjust(char *str, const char *search)