MIPS: Sibyte: Export symbol periph_rev to sb1250-mac network driver.
This fixes the following modpost error:

ERROR: "periph_rev" [drivers/net/ethernet/broadcom/sb1250-mac.ko] undefined!

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit b91a59cf10a7d69a2669cda009c2943640b11168)