fix
../arch/powerpc/kernel/prom.c: In function 'early_reserve_mem':
../arch/powerpc/kernel/prom.c:618:10: error: variable 'reserve_map' set
but not used [-Werror=unused-but-set-variable]
  __be64 *reserve_map;
          ^~~~~~~~~~~