fix
../arch/powerpc/kernel/sysfs.c: In function 'sysfs_create_dscr_default':
../arch/powerpc/kernel/sysfs.c:594:7: error: variable 'err' set but not
used [-Werror=unused-but-set-variable]
   int err = 0;